Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,8 +1,39 @@
+# This file is a template, and might need editing before it works on your project.
+# Auto DevOps
+# This CI/CD configuration provides a standard pipeline for
+# * building a Docker image (using a buildpack if necessary),
+# * storing the image in the container registry,
+# * running tests from a buildpack,
+# * running code quality analysis,
+# * creating a review app for each topic branch,
+# * and continuous deployment to production
+#
+# In order to deploy, you must have a working sloppy.io Account 
+# via a project integration, or via group/project variables.
+# AUTO_DEVOPS_DOMAIN must also be set as a variable at the group or project
+# level, or manually added below.
+#
+# If you want to deploy to staging first, or enable canary deploys,
+# uncomment the relevant jobs in the pipeline below.
+#
+# If Auto DevOps fails to detect the proper buildpack, or if you want to
+# specify a custom buildpack, set a project variable `BUILDPACK_URL` to the
+# repository URL of the buildpack.
+# e.g. BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git#v142
+# If you need multiple buildpacks, add a file to your project called
+# `.buildpacks` that contains the URLs, one on each line, in order.
+# Note: Auto CI does not work with multiple buildpacks yet
+
 image: alpine:latest
 
 variables:
   # AUTO_DEVOPS_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
   # AUTO_DEVOPS_DOMAIN: domain.example.com
+
+  POSTGRES_USER: user
+  POSTGRES_PASSWORD: testing-password
+  POSTGRES_ENABLED: "true"
+  POSTGRES_DB: $CI_ENVIRONMENT_SLUG
 
 stages:
   - build
@@ -25,8 +56,8 @@ build:
     - build
   only:
     - branches
-
-# Configure your own tests
+    
+# Example for running tests. Write your own ones
 .test:
   services:
     - postgres:latest
@@ -59,10 +90,10 @@ review:
   script:
     - check_kube_domain
     - install_dependencies
-    - download_chart
+    #- download_chart
     - ensure_namespace
-    - install_tiller
-    - create_secret
+    #- install_tiller
+    #- create_secret
     - deploy
   environment:
     name: review/$CI_COMMIT_REF_NAME
@@ -149,12 +180,14 @@ staging:
 production:
   stage: production
   script:
-  # check if AUTO_DEVOPS_DOMAIN is set
+  # checkt ob AUTO_DEVOPS_DOMAIN gesetzt ist
     - check_kube_domain
     - install_dependencies
-    # check if project/namespace exist
+    # - download_chart
+    # checkt ob es das projekt/namespace gibt
     - ensure_namespace
     - deploy
+    # - delete canary
   environment:
     name: production
     url: https://$SLOPPY_PROJECTNAME-production.$AUTO_DEVOPS_DOMAIN
@@ -240,7 +273,6 @@ production:
     fi
   }
 
-# example for seting up a test db
   function setup_test_db() {
     if [ -z ${KUBERNETES_PORT+x} ]; then
       DB_HOST=postgres
@@ -251,9 +283,11 @@ production:
   }
 
   function ensure_namespace() {
-    CLEANED_CI_ENVIRONMENT_NAME="${CI_ENVIRONMENT_NAME/\//-}" # replace "/"" with "-"" or sloppy projectname is invalid
-    echo "Doing: sloppy start --var=domain:$CI_PROJECT_PATH_SLUG.$AUTO_DEVOPS_DOMAIN --var=project:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME --var=image:$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG sloppy.yml"
-    sloppy show $SLOPPY_PROJECTNAME-$CI_ENVIRONMENT_NAME || sloppy start --var=domain:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME.$AUTO_DEVOPS_DOMAIN --var=project:$SLOPPY_PROJECTNAME-$CI_ENVIRONMENT_NAME --var=image:$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG sloppy.yml
+    CLEANED_CI_ENVIRONMENT_NAME=$( echo ${CI_ENVIRONMENT_NAME//\//-} | sed  s/review/r/g | cut -c 1-23 ) # replace "/"" with "-"" or sloppy projectname is invalid. Also shorten to 23 chars or the fqdn might be to long!
+    echo "CLEANED_CI_ENVIRONMENT_NAME=$CLEANED_CI_ENVIRONMENT_NAME"
+    
+    echo "Doing: sloppy show $SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME || sloppy start --var=domain:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME.$AUTO_DEVOPS_DOMAIN --var=project:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME --var=image:$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG sloppy.yml"
+                 sloppy show $SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME || sloppy start --var=domain:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME.$AUTO_DEVOPS_DOMAIN --var=project:$SLOPPY_PROJECTNAME-$CLEANED_CI_ENVIRONMENT_NAME --var=image:$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG sloppy.yml
   }
 
   function check_kube_domain() {
@@ -302,7 +336,8 @@ production:
       name="$name-$track"
     fi
 
-    helm delete "$name" || true
+    # helm delete "$name" || true
+    sloppy delete "$name"
   }
 
 before_script:
